name: productiv API Vocabulary
provider: productiv
created: '2026-04-18'
modified: '2026-04-18'
operations: 15
schemas: 2
tags:
- App Details
- App Summaries
- Applications
- Audit Events
- Authentication
- Batch Upload
- Org Chart
- Provisioned Users
- Provisioning Workflows
- Spend Data
- Usage Events
